import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from './navbar/page';
import '@radix-ui/themes/styles.css';
import { Container, Theme } from '@radix-ui/themes';
import './theme-config.css';
import AuthProvider from './auth/Provider';
import ReactQueryProvider from './ReactQueryProvider';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.variable}>
        <ReactQueryProvider>
          <AuthProvider>
            <Theme>
              <NavBar />
              <main className='m-8'>
                <Container>{children}</Container>
              </main>
            </Theme>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
